added dw conv mapping
ucb-bar/gemmini pull request #104
Opened 2021-04-08 06:21 UTC by SeahK

2021-04-08 23:14 UTC, hngenc commented on src/main/scala/gemmini/LoopConv.scala
> +		  loop_being_configured.depthwise := cmd.bits.rs2(63)
Can you use spaces for tabbing here?

2021-04-08 23:15 UTC, hngenc requested changes
1. Have you double-checked that this doesn't stall on Firesim?
2. Can you also bump gemmini-rocc-tests within this PR?

2022-07-21 09:03 UTC, fPecc commented
Hi @SeahK,

Do we have a measure on how much this improves the current depthwise convolution  solution? I mean, if the change you made in gemmini-rocc-tests is also merged.

Thanks!

2022-09-11 05:35 UTC, hngenc commented
@fPecc This PR is out-of-date. Fortunately, we already have an improved depthwise conv which was added to Gemmini's `master` branch. We  use it for our hand-written Mobilenet implementation (as shown [here](https://github.com/ucb-bar/gemmini-rocc-tests/blob/e326e7c43457ff08669fe88edcaa395d846474d8/imagenet/mobilenet.c#L120)).

Performance is still pretty poor, but the improvement made it much better. (I don't remember exactly how much faster it made it though).

2022-09-11 05:35 UTC, closed without merging